language: android

dist: trusty

jdk: oraclejdk8

android:
  components:
    - tools
    - tools # Running this twice get's the latest build tools (https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI)
    - platform-tools
    - build-tools-${ANDROID_BUILD_TOOLS}
    - android-${ANDROID_API}
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - yes | sdkmanager "platforms;android-27"

install: ./gradlew ":$MODULE:build" ":$MODULE:assemble" --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.0
  matrix:
    - MODULE=rxflux-core
    - MODULE=rxflux-android

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle